pipeline {
  agent any

  stages {
    stage('Build Docker Image') {
      steps {
        bat 'docker build -t my-python-app Jenkins/python_app'
      }
    }

 stage('Run Unit Tests') {
  steps {
    bat 'docker run --rm my-python-app python -m unittest discover test'
  }
}

   stage('Deploy') {
      steps {
        bat 'docker run -d -p 5000:5000 --name my-python-container my-python-app'
      }
    }
  }

  post {
    always {
      echo '✅ Pipeline finished!'
    }
  }
}
