pipeline {
  agent any

  stages {
    stage('Build Docker Image') {
      steps {
        bat 'docker build -t my-python-app Jenkins/python_app'
      }
    }

    stage('Check Python') {
  steps {
    bat 'where python'
  }
}

stage('Run Unit Tests') {
  steps {
    bat '''
      py -m venv venv
      call venv\\Scripts\\activate.bat
      pip install -r requirements.txt
      py -m unittest discover tests
    '''
  }
}


    stage('Deploy') {
      steps {
        bat 'docker run -d -p 5000:5000 --name my-python-container my-python-app'
      }
    }
  }

  post {
    always {
      echo '✅ Pipeline finished!'
    }
  }
}
