pipeline {
  agent any

  environment {
    VENV_DIR = "venv"
  }

  stages {
    stage('Checkout') {
      steps {
        // Clone the actual GitHub repo (replace with your real one)
        git 'https://github.com/ABIRAMI1997/Devops.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        bat 'docker build -t my-python-app .'
      }
    }

    stage('Run Unit Tests') {
      steps {
        bat """
        python -m venv %VENV_DIR%
        call %VENV_DIR%\\Scripts\\activate.bat
        pip install -r requirements.txt
        python -m unittest discover -s tests
        """
      }
    }

    stage('Deploy') {
      steps {
        bat 'docker run -d -p 5000:5000 --name my-python-container my-python-app'
      }
    }
  }

  post {
    always {
      echo '✅ Pipeline finished!'
    }
  }
}
